spring:

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

  batch:
    job:
      enabled: false

  data:
    mongodb:
      host: localhost
      port: 0
      database: library

  datasource:
    url: jdbc:h2:mem:maindb
    driverClassName: org.h2.Driver
    username: sa
    password:

    h2:
      console:
        enabled: true
        path: /h2-console

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  enabled: true
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - com.example.hw13spring_batch.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local